lecture3/hello/urls.py
from django.urls import path
# . means the currentf directory
from . import views

urlpatterns = [
    path("", views.index , name="index" ) , 
    path("hello" , views.hello , name="hello"),
    path("batman" , views.batman, name="batman"),
    #any path string is a url pattern
    path("<str:name>" , views.greet , name="greet")
    
    ]   

lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hello/" , include("hello.urls")),
    path("newyear/" , include("newyear.urls")),
    path("tasks/" , include("tasks.urls"))
]

lecture3/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index")
]

lecture3/tasks/urls.py
from django.urls import path
from . import views
app_name = "tasks"
urlpatterns = [
    path("" , views.index , name="index"),
    path("add" , views.add,name="add")
]

lecture3/hello/models.py
from django.db import models

# Create your models here.

lecture3/newyear/models.py
from django.db import models

# Create your models here.

lecture3/tasks/models.py
from django.db import models

# Create your models here.

lecture3/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
 
# each view is something that the user might wanna see

def index(request):
    return render(request , "hello/index.html")

def hello(request):
    return HttpResponse("Hello, Parsa!")

def batman(request):
    return HttpResponse("something in the way mmmmm")
# httpresponses can be any html content 
def greet(request , name):
    return render(request, "hello./greet.html", {
        "name" : name.capitalize()
    })

lecture3/newyear/views.py
from django.shortcuts import render
import datetime
now = datetime.datetime.now()
# Create your views here.
def index(request):
    return render(request, "newyear/index.html" , {
        "newyear" : now.month == 1 and now.day == 1
    })

lecture3/tasks/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse



class NewTaskForm(forms.Form):
    task = forms.CharField(label="New task")
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)


def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request, "tasks/index.html" , {
        #the variable on the right is the python variable
        # the variable on the left is the html variable that django will have access
        # over all they are keys and values
        "tasks" : request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html" , {
                "form" : form
            })
        
    return render(request, "tasks/add.html" , {
        "form" : NewTaskForm()
    })

lecture3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html>
    <head>
        <title>Greet!</title>
    </head>
    <body>
        <h1>Hello, {{name}}!</h1>
    </body>
</html>

lecture3/hello/templates/hello/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>hello!</title>
    </head>
    <body>
        Hello, World
    </body>
</html>

lecture3/newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Newyear ? </title>
        <link rel="stylesheet" href="{% static 'newyear/styles.css'%}">
    </head>
    <body>
        {% if newyear%}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

lecture3/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        <h1>Add task</h1>
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}
f

lecture3/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
        <ul>
            {% for task in tasks %}
                <li>{{ task }}</li>
            {% empty %}
                <li>No tasks </li>
            {% endfor %}
        </ul>
        <a href="{% url 'tasks:add' %}">Add a new task </a>
{% endblock %}

lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>